name: "clang-format Check"
description: "Use clang-format to see if your C code is formatted according to project guidelines."

branding:
  icon: "check-circle"
  color: "blue"

inputs:
  findString:
    description: 'What is the find string to use in the shell script'
    required: false
    default: '*.proto'
  searchPath:
    description: 'What is the search path to use in the shell script'
    required: false
    default: '.'

runs:
  using: "docker"
  image: "Dockerfile"